GET http://localhost:8080/user/test
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2huLmRvZTZAZXhhbXBsZS5jb20iLCJpYXQiOjE3NTA1MTQ1NDUsImV4cCI6MTg5MDU1NTcwODk3ODAwfQ.NeXaqXxeKvh_VSe7x_EDL7x_JvXNVpCkfShxFv2iuYw
Content-Type: application/json