spring:

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID_GOOGLE}
            client-secret: ${CLIENT_SECRET_GOOGLE}
            scope:
              - email
              - profile
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Google

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  profiles:
    active: ${APP_PROFILE:local}
  application:
    name: sip-api

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/sip}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASS:postgres}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: SpringBootJPAHikariCP
      minimumIdle: 15
      maximumPoolSize: 50
      connectionTimeout: 30000
      idleTimeout: 30000
  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: ${KAFKA_URL:localhost:9093}
    consumer:
      notification:
        group-id: notification-sender
        topic: notification
        factory: notificationKafkaListenerContainerFactory
      email:
        group-id: email-sender
        topic: email
        factory: emailKafkaListenerContainerFactory

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:example@sip.com}
    password: ${EMAIL_PASSWORD:12345678}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: "*"
    default-encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


security:
  token:
    jwt:
      expiration: ${SECURITY_JWT_EXPIRATION_EM_HORAS:8}
      secret: ${SECURITY_JWT_SECRET:1234567abcdeABCDE}

server:
  servlet:
    context-path: /sip/api

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

minio:
  endpoint: ${MINIO_ENDPOINT:http://192.168.1.2:9000}
  accessKey: ${MINIO_ACCESS:admin}
  secretKey: ${MINIO_SECRET:admin123}
  bucketProfile: ${MINIO_BUCKET_PROFILE:profimage}
  bucketItems: ${MINIO_BUCKET_ITEMS:itemsimage}
  application:
    max_images_item: ${MAX_IMAGE_ITEM:3}

sip:
  root:
    email: ${ROOT_EMAIL:root@sip.com}
    password: ${ROOT_PASS:SenhaSegura@123}
    name: ${ROOT_NAME:Root Admin}
    phone: ${ROOT_PHONE:71999998888}
    cpf: ${ROOT_CPF:00000000000}

application:
  front-end:
    url: ${FRONTEND_APPLICATION_URL:http://localhost:3000}
  time:
    donation: ${DONATION_TIME_DAYS:180}
    about-to-donate: ${ABOUT_TO_DONATE:30}
  item:
    max-active-requests: ${MAX_ACTIVE-REQUESTS:5}



