spring:
  application:
    name: sip-api
    baseUrl: http://localhost:8080

  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/sip}
    username: ${DATASOURCE_USER:postgres}
    password: ${DATASOURCE_PASS:postgres}
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: SpringBootJPAHikariCP
      minimumIdle: 15
      maximumPoolSize: 50
      connectionTimeout: 30000
      idleTimeout: 30000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      email-verification:
        group-id: email-verification-sender
        topic: email-verification
        factory: emailVerificationKafkaListenerContainerFactory

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:example@sip.com}
    password: ${EMAIL_PASSWORD:12345678}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

security:
  token:
    jwt:
      expiration: ${SECURITY_JWT_EXPIRATION_EM_HORAS:8}
      secret: ${SECURITY_JWT_SECRET:1234567abcdeABCDE}